
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Locale;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arad
 */
public class OrderingSystem extends javax.swing.JFrame {

    /**
     * Creates new form OrderingSystem
     */
    public OrderingSystem() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
       btnorder.setBackground(Color.DARK_GRAY);
       btnGame.setBackground(Color.DARK_GRAY);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgMenu = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dlg_lstOrder = new javax.swing.JList<>();
        dlg_tfTotal = new javax.swing.JTextField();
        dlg_btnRemove = new javax.swing.JButton();
        dlg_btnPeyment = new javax.swing.JButton();
        dlg_lblTotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        dlgMe_MianDish = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        dlgMe_MaineDish = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        dlgMe_Dessert = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        dlgMe_Hot = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        dlgMe_Cold = new javax.swing.JMenuItem();
        dlgPeyment = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        dlgLogIn = new javax.swing.JDialog();
        dlgLogIn_lblUser = new javax.swing.JLabel();
        dlgLogin_lblPassword = new javax.swing.JLabel();
        dlgLogIn_tfUser = new javax.swing.JTextField();
        dlgLogIn_tfPass = new javax.swing.JTextField();
        dlgLogIn_btnCancel = new javax.swing.JButton();
        dlgLogIn_btnOk1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnorder = new javax.swing.JButton();
        btnGame = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        dlgMenu.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel2.setText("jLabel2");
        dlgMenu.getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(null);

        dlg_lstOrder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dlg_lstOrder);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 160, 310);

        dlg_tfTotal.setText("00.00");
        jPanel2.add(dlg_tfTotal);
        dlg_tfTotal.setBounds(110, 360, 80, 30);

        dlg_btnRemove.setText("remove");
        jPanel2.add(dlg_btnRemove);
        dlg_btnRemove.setBounds(480, 360, 69, 23);

        dlg_btnPeyment.setText("peyment");
        jPanel2.add(dlg_btnPeyment);
        dlg_btnPeyment.setBounds(560, 360, 75, 23);

        dlg_lblTotal.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        dlg_lblTotal.setForeground(new java.awt.Color(204, 204, 204));
        dlg_lblTotal.setText("Total");
        jPanel2.add(dlg_lblTotal);
        dlg_lblTotal.setBounds(30, 360, 80, 33);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ipd11\\Documents\\Java3OrderingSystem\\OrderingSystem\\image\\Background6.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 700, 460);

        dlgMenu.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Menu");

        dlgMe_MianDish.setText("Starter");
        dlgMe_MianDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgMe_MianDishActionPerformed(evt);
            }
        });
        jMenu2.add(dlgMe_MianDish);
        jMenu2.add(jSeparator1);

        dlgMe_MaineDish.setText("Maine Dish");
        jMenu2.add(dlgMe_MaineDish);
        jMenu2.add(jSeparator2);

        dlgMe_Dessert.setText("Dessert");
        dlgMe_Dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgMe_DessertActionPerformed(evt);
            }
        });
        jMenu2.add(dlgMe_Dessert);
        jMenu2.add(jSeparator3);

        dlgMe_Hot.setText("Hot Drink");
        dlgMe_Hot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgMe_HotActionPerformed(evt);
            }
        });
        jMenu2.add(dlgMe_Hot);
        jMenu2.add(jSeparator4);

        dlgMe_Cold.setText("Cold Drink");
        jMenu2.add(dlgMe_Cold);

        jMenuBar2.add(jMenu2);

        dlgMenu.setJMenuBar(jMenuBar2);

        dlgPeyment.setMinimumSize(new java.awt.Dimension(700, 500));

        jLabel5.setText("jLabel5");
        dlgPeyment.getContentPane().add(jLabel5, java.awt.BorderLayout.PAGE_END);

        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        dlgPeyment.getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        dlgLogIn_lblUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dlgLogIn_lblUser.setText("User name:");

        dlgLogin_lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dlgLogin_lblPassword.setText("password:");

        dlgLogIn_btnCancel.setText("Cancele");
        dlgLogIn_btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgLogIn_btnCancelActionPerformed(evt);
            }
        });

        dlgLogIn_btnOk1.setText("OK");
        dlgLogIn_btnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgLogIn_btnOk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgLogInLayout = new javax.swing.GroupLayout(dlgLogIn.getContentPane());
        dlgLogIn.getContentPane().setLayout(dlgLogInLayout);
        dlgLogInLayout.setHorizontalGroup(
            dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLogInLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dlgLogin_lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dlgLogIn_lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dlgLogIn_tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgLogIn_tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgLogInLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(dlgLogIn_btnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(dlgLogIn_btnCancel)
                .addGap(112, 112, 112))
        );
        dlgLogInLayout.setVerticalGroup(
            dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLogInLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dlgLogIn_lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgLogInLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(dlgLogIn_tfUser)))
                .addGap(18, 18, 18)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgLogin_lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgLogIn_tfPass))
                .addGap(39, 39, 39)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgLogIn_btnCancel)
                    .addComponent(dlgLogIn_btnOk1))
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(null);

        btnorder.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnorder.setText("Order");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        jPanel1.add(btnorder);
        btnorder.setBounds(270, 150, 180, 60);

        btnGame.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnGame.setText("Game");
        btnGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGameActionPerformed(evt);
            }
        });
        jPanel1.add(btnGame);
        btnGame.setBounds(270, 240, 180, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ipd11\\Documents\\Java3OrderingSystem\\OrderingSystem\\image\\Background6.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 450);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("log in");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGameActionPerformed
        // TODO add your handling code here:
        
        dlgMenu.pack();
        dlgMenu.setVisible(true);
    }//GEN-LAST:event_btnGameActionPerformed

    private void dlgMe_MianDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgMe_MianDishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgMe_MianDishActionPerformed

    private void dlgMe_DessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgMe_DessertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgMe_DessertActionPerformed

    private void dlgMe_HotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgMe_HotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgMe_HotActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        // TODO add your handling code here:
        
        dlgMenu.pack();
        dlgMenu.setVisible(true);
    }//GEN-LAST:event_btnorderActionPerformed

    private void dlgLogIn_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgLogIn_btnCancelActionPerformed
        // TODO add your handling code here:
        dlgLogIn.setVisible(false);
    }//GEN-LAST:event_dlgLogIn_btnCancelActionPerformed

    private void dlgLogIn_btnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgLogIn_btnOk1ActionPerformed
        // TODO add your handling code here:
       // String user=dlgLogIn_tfUser.getText().toLowerCase();
       // String pass=dlgLogIn_tfPass.getText().toLowerCase();
//        if(user=="admin"){
//            
//            if(pass="admin")
//                dlgadmin.setVisible(true);
//        }
//                        
//        
//        }
//    else
    
    }//GEN-LAST:event_dlgLogIn_btnOk1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        
        dlgLogIn.pack();
        dlgLogIn.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGame;
    private javax.swing.JButton btnorder;
    private javax.swing.JDialog dlgLogIn;
    private javax.swing.JButton dlgLogIn_btnCancel;
    private javax.swing.JButton dlgLogIn_btnOk1;
    private javax.swing.JLabel dlgLogIn_lblUser;
    private javax.swing.JTextField dlgLogIn_tfPass;
    private javax.swing.JTextField dlgLogIn_tfUser;
    private javax.swing.JLabel dlgLogin_lblPassword;
    private javax.swing.JMenuItem dlgMe_Cold;
    private javax.swing.JMenuItem dlgMe_Dessert;
    private javax.swing.JMenuItem dlgMe_Hot;
    private javax.swing.JMenuItem dlgMe_MaineDish;
    private javax.swing.JMenuItem dlgMe_MianDish;
    private javax.swing.JDialog dlgMenu;
    private javax.swing.JDialog dlgPeyment;
    private javax.swing.JButton dlg_btnPeyment;
    private javax.swing.JButton dlg_btnRemove;
    private javax.swing.JLabel dlg_lblTotal;
    private javax.swing.JList<String> dlg_lstOrder;
    private javax.swing.JTextField dlg_tfTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
