
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arad
 */
public class OrderingSystem extends javax.swing.JFrame {

    /**
     * Creates new form OrderingSystem
     */
    public OrderingSystem() {
        initComponents();
        
        //Centrize the Form
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        //change the color of buttons
       btnorder.setBackground(Color.DARK_GRAY);
       btnGame.setBackground(Color.DARK_GRAY);
       
       
      
       
       //add date and time to the status bar
       
       DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
       Calendar cal = Calendar.getInstance();
       dlgMenu_lblDate.setText(dateFormat.format(cal.getTime()));
       
       
       dlgPeyment_lblStatus.setText(dateFormat.format(cal.getTime()));
       
       
       
       
     //add image to the button  
//    ImageIcon water = new ImageIcon("water.bmp");
//    JButton button = new JButton(water);
//    frame.add(button);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgMenu = new javax.swing.JDialog();
        dlgMenu_lblDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dlg_lstOrder = new javax.swing.JList<>();
        dlg_tfTotal = new javax.swing.JTextField();
        dlgMenu_btnRemove = new javax.swing.JButton();
        dlgMenu_btnPeyment = new javax.swing.JButton();
        dlg_lblTotal = new javax.swing.JLabel();
        dlgmenu_lblPic2 = new javax.swing.JLabel();
        dlgmenu_lblPic1 = new javax.swing.JLabel();
        dlgmenu_lblPic4 = new javax.swing.JLabel();
        dlgmenu_lblPic3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        dlgMe_MianDish = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        dlgMe_MaineDish = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        dlgMe_Dessert = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        dlgMe_Hot = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        dlgMe_Cold = new javax.swing.JMenuItem();
        dlgPeyment = new javax.swing.JDialog();
        dlgPeyment_lblStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dlgPement_tfTotal = new javax.swing.JTextField();
        dlgPeyment_cbTip = new javax.swing.JComboBox<>();
        dlgPeyment_btnSave = new javax.swing.JButton();
        dlgPeyment_btnSavePrint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dlgLogIn = new javax.swing.JDialog();
        dlgLogIn_lblUser = new javax.swing.JLabel();
        dlgLogin_lblPassword = new javax.swing.JLabel();
        dlgLogIn_tfUser = new javax.swing.JTextField();
        dlgLogIn_tfPass = new javax.swing.JTextField();
        dlgLogIn_btnCancel = new javax.swing.JButton();
        dlgLogIn_btnOk1 = new javax.swing.JButton();
        dlgLogIn_lblMessage = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnorder = new javax.swing.JButton();
        btnGame = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

<<<<<<< HEAD
        dlgMenu.setPreferredSize(new java.awt.Dimension(700, 500));
        dlgMenu.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dlgMenuWindowOpened(evt);
            }
        });

=======
>>>>>>> origin/master
        dlgMenu_lblDate.setText("jLabel2");
        dlgMenu.getContentPane().add(dlgMenu_lblDate, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(null);

        dlg_lstOrder.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dlg_lstOrder);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 160, 310);

        dlg_tfTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dlg_tfTotal.setText("00.00");
        jPanel2.add(dlg_tfTotal);
        dlg_tfTotal.setBounds(90, 360, 80, 30);

        dlgMenu_btnRemove.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        dlgMenu_btnRemove.setText("remove");
        dlgMenu_btnRemove.setMaximumSize(new java.awt.Dimension(80, 35));
        dlgMenu_btnRemove.setMinimumSize(new java.awt.Dimension(80, 35));
        dlgMenu_btnRemove.setPreferredSize(new java.awt.Dimension(80, 35));
        jPanel2.add(dlgMenu_btnRemove);
        dlgMenu_btnRemove.setBounds(390, 360, 100, 35);

        dlgMenu_btnPeyment.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        dlgMenu_btnPeyment.setText("peyment");
        dlgMenu_btnPeyment.setMaximumSize(new java.awt.Dimension(80, 35));
        dlgMenu_btnPeyment.setPreferredSize(new java.awt.Dimension(80, 35));
        dlgMenu_btnPeyment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgMenu_btnPeymentActionPerformed(evt);
            }
        });
        jPanel2.add(dlgMenu_btnPeyment);
        dlgMenu_btnPeyment.setBounds(510, 360, 100, 35);

        dlg_lblTotal.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        dlg_lblTotal.setForeground(new java.awt.Color(204, 204, 204));
        dlg_lblTotal.setText("Total");
        jPanel2.add(dlg_lblTotal);
        dlg_lblTotal.setBounds(10, 360, 80, 33);

        dlgmenu_lblPic2.setText("picture");
        jPanel2.add(dlgmenu_lblPic2);
        dlgmenu_lblPic2.setBounds(540, 50, 90, 100);

        dlgmenu_lblPic1.setText("picture");
        jPanel2.add(dlgmenu_lblPic1);
        dlgmenu_lblPic1.setBounds(400, 190, 90, 100);

        dlgmenu_lblPic4.setText("picture");
        jPanel2.add(dlgmenu_lblPic4);
        dlgmenu_lblPic4.setBounds(540, 190, 90, 100);

        dlgmenu_lblPic3.setText("picture");
        jPanel2.add(dlgmenu_lblPic3);
        dlgmenu_lblPic3.setBounds(400, 50, 90, 100);

<<<<<<< HEAD
=======
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\arad\\Documents\\JavaOrderingSystemProj\\OrderingSystem\\image\\Background6.jpg")); // NOI18N
>>>>>>> 82a3d100fd2e78fbb633b3d281473980e1f56903
        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 700, 460);

        dlgMenu.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Menu");

        dlgMe_MianDish.setText("Starter");
        dlgMe_MianDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgMe_MianDishActionPerformed(evt);
            }
        });
        jMenu2.add(dlgMe_MianDish);
        jMenu2.add(jSeparator1);

        dlgMe_MaineDish.setText("Maine Dish");
        jMenu2.add(dlgMe_MaineDish);
        jMenu2.add(jSeparator2);

        dlgMe_Dessert.setText("Dessert");
        dlgMe_Dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgMe_DessertActionPerformed(evt);
            }
        });
        jMenu2.add(dlgMe_Dessert);
        jMenu2.add(jSeparator3);

        dlgMe_Hot.setText("Hot Drink");
        dlgMe_Hot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgMe_HotActionPerformed(evt);
            }
        });
        jMenu2.add(dlgMe_Hot);
        jMenu2.add(jSeparator4);

        dlgMe_Cold.setText("Cold Drink");
        jMenu2.add(dlgMe_Cold);

        jMenuBar2.add(jMenu2);

        dlgMenu.setJMenuBar(jMenuBar2);

        dlgPeyment.setMinimumSize(new java.awt.Dimension(700, 500));
        dlgPeyment.setPreferredSize(new java.awt.Dimension(700, 500));

        dlgPeyment_lblStatus.setText("jLabel2");
        dlgPeyment.getContentPane().add(dlgPeyment_lblStatus, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(110, 60, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Tip");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(100, 120, 90, 30);

        dlgPement_tfTotal.setText("jTextField1");
        jPanel3.add(dlgPement_tfTotal);
        dlgPement_tfTotal.setBounds(220, 60, 110, 30);

        dlgPeyment_cbTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Amount", "Percentage", " " }));
        jPanel3.add(dlgPeyment_cbTip);
        dlgPeyment_cbTip.setBounds(220, 120, 110, 30);

        dlgPeyment_btnSave.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        dlgPeyment_btnSave.setText("Save");
        jPanel3.add(dlgPeyment_btnSave);
        dlgPeyment_btnSave.setBounds(240, 220, 120, 30);

        dlgPeyment_btnSavePrint.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        dlgPeyment_btnSavePrint.setText("Save&Print");
        jPanel3.add(dlgPeyment_btnSavePrint);
        dlgPeyment_btnSavePrint.setBounds(90, 220, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(20, 120, 55, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\arad\\Documents\\JavaOrderingSystemProj\\OrderingSystem\\image\\Background6.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 480);

        dlgPeyment.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        dlgLogIn_lblUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dlgLogIn_lblUser.setText("User name:");

        dlgLogin_lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dlgLogin_lblPassword.setText("password:");

        dlgLogIn_btnCancel.setText("Cancele");
        dlgLogIn_btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgLogIn_btnCancelActionPerformed(evt);
            }
        });

        dlgLogIn_btnOk1.setText("OK");
        dlgLogIn_btnOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgLogIn_btnOk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgLogInLayout = new javax.swing.GroupLayout(dlgLogIn.getContentPane());
        dlgLogIn.getContentPane().setLayout(dlgLogInLayout);
        dlgLogInLayout.setHorizontalGroup(
            dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgLogInLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(dlgLogIn_btnOk1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(dlgLogIn_btnCancel)
                .addGap(112, 112, 112))
            .addGroup(dlgLogInLayout.createSequentialGroup()
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dlgLogInLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dlgLogIn_lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlgLogInLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dlgLogin_lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dlgLogIn_lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dlgLogIn_tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlgLogIn_tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgLogInLayout.setVerticalGroup(
            dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLogInLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dlgLogIn_lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgLogInLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(dlgLogIn_tfUser)))
                .addGap(18, 18, 18)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgLogin_lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlgLogIn_tfPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dlgLogIn_lblMessage)
                .addGap(14, 14, 14)
                .addGroup(dlgLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlgLogIn_btnCancel)
                    .addComponent(dlgLogIn_btnOk1))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(null);

        btnorder.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnorder.setText("Order");
        btnorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderActionPerformed(evt);
            }
        });
        jPanel1.add(btnorder);
        btnorder.setBounds(270, 150, 180, 60);

        btnGame.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnGame.setText("Game");
        btnGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGameActionPerformed(evt);
            }
        });
        jPanel1.add(btnGame);
        btnGame.setBounds(270, 240, 180, 60);

<<<<<<< HEAD
=======
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\arad\\Documents\\JavaOrderingSystemProj\\OrderingSystem\\image\\Background6.jpg")); // NOI18N
>>>>>>> 82a3d100fd2e78fbb633b3d281473980e1f56903
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 450);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("log in");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGameActionPerformed
        // TODO add your handling code here:
        
        dlgMenu.pack();
        dlgMenu.setVisible(true);
    }//GEN-LAST:event_btnGameActionPerformed

    private void dlgMe_MianDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgMe_MianDishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgMe_MianDishActionPerformed

    private void dlgMe_DessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgMe_DessertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgMe_DessertActionPerformed

    private void dlgMe_HotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgMe_HotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlgMe_HotActionPerformed

    private void btnorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderActionPerformed
        // TODO add your handling code here:
        
        dlgMenu.pack();
        dlgMenu.setVisible(true);
        
    }//GEN-LAST:event_btnorderActionPerformed

    private void dlgLogIn_btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgLogIn_btnCancelActionPerformed
        // TODO add your handling code here:
        dlgLogIn.setVisible(false);
    }//GEN-LAST:event_dlgLogIn_btnCancelActionPerformed

    private void dlgLogIn_btnOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgLogIn_btnOk1ActionPerformed
        // TODO add your handling code here:
        
       
//       String user=dlgLogIn_tfUser.getText().toLowerCase();
//       String pass=dlgLogIn_tfPass.getText();
       String errors="";
       String admin="admin";
        if(!dlgLogIn_tfUser.getText().toLowerCase().equals(admin)){
            errors += " Invalid User Nsme ";
        }
        if(!dlgLogIn_tfPass.getText().equals(admin)){
            errors += "Invalid  Password .\n";
        }
                              
        
        
        if (errors.isEmpty()) {
            dlgLogIn_lblMessage.setText("you are Log In");
            //dlgLogIn.setVisible(false);
            //dlgadmin.pack(true);
            //dlgadmin.setVisible(true);
           
        }
        else {
            
            dlgLogIn_lblMessage.setText("");
            
            JOptionPane.showMessageDialog(this,
                        errors,
                        "LogIn Error",
                        JOptionPane.ERROR_MESSAGE);
         }
    
    }//GEN-LAST:event_dlgLogIn_btnOk1ActionPerformed
    
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        
        dlgLogIn.pack();
        dlgLogIn.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void dlgMenuWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgMenuWindowOpened
        // TODO add your handling code here:
                dlgMenu_btnRemove.setBackground(Color.DARK_GRAY);
                dlgMenu_btnPeyment.setBackground(Color.DARK_GRAY);
                
                 

    }//GEN-LAST:event_dlgMenuWindowOpened

    private void dlgMenu_btnPeymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgMenu_btnPeymentActionPerformed
        // TODO add your handling code here:
        
        dlgPeyment.pack();
        dlgPeyment.setVisible(true);
        
    }//GEN-LAST:event_dlgMenu_btnPeymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dlgMenu.pack();
        dlgMenu.setVisible(true);
        dlgPeyment.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGame;
    private javax.swing.JButton btnorder;
    private javax.swing.JDialog dlgLogIn;
    private javax.swing.JButton dlgLogIn_btnCancel;
    private javax.swing.JButton dlgLogIn_btnOk1;
    private javax.swing.JLabel dlgLogIn_lblMessage;
    private javax.swing.JLabel dlgLogIn_lblUser;
    private javax.swing.JTextField dlgLogIn_tfPass;
    private javax.swing.JTextField dlgLogIn_tfUser;
    private javax.swing.JLabel dlgLogin_lblPassword;
    private javax.swing.JMenuItem dlgMe_Cold;
    private javax.swing.JMenuItem dlgMe_Dessert;
    private javax.swing.JMenuItem dlgMe_Hot;
    private javax.swing.JMenuItem dlgMe_MaineDish;
    private javax.swing.JMenuItem dlgMe_MianDish;
    private javax.swing.JDialog dlgMenu;
    private javax.swing.JButton dlgMenu_btnPeyment;
    private javax.swing.JButton dlgMenu_btnRemove;
    private javax.swing.JLabel dlgMenu_lblDate;
    private javax.swing.JTextField dlgPement_tfTotal;
    private javax.swing.JDialog dlgPeyment;
    private javax.swing.JButton dlgPeyment_btnSave;
    private javax.swing.JButton dlgPeyment_btnSavePrint;
    private javax.swing.JComboBox<String> dlgPeyment_cbTip;
    private javax.swing.JLabel dlgPeyment_lblStatus;
    private javax.swing.JLabel dlg_lblTotal;
    private javax.swing.JList<String> dlg_lstOrder;
    private javax.swing.JTextField dlg_tfTotal;
    private javax.swing.JLabel dlgmenu_lblPic1;
    private javax.swing.JLabel dlgmenu_lblPic2;
    private javax.swing.JLabel dlgmenu_lblPic3;
    private javax.swing.JLabel dlgmenu_lblPic4;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
